export interface VehicleModel {
  name: string;
  fuelTypes: string[];
}

export interface VehicleMake {
  name: string;
  models: VehicleModel[];
}

export const VEHICLE_DATA: VehicleMake[] = [
  {
    name: "Maruti Suzuki",
    models: [
      { name: "Alto", fuelTypes: ["Petrol", "CNG"] },
      { name: "Alto K10", fuelTypes: ["Petrol", "CNG"] },
      { name: "Alto 800", fuelTypes: ["Petrol", "CNG"] },
      { name: "Swift", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "Swift Dzire", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "Baleno", fuelTypes: ["Petrol", "CNG"] },
      { name: "Wagon R", fuelTypes: ["Petrol", "CNG"] },
      { name: "Celerio", fuelTypes: ["Petrol", "CNG"] },
      { name: "S-Presso", fuelTypes: ["Petrol", "CNG"] },
      { name: "Ignis", fuelTypes: ["Petrol"] },
      { name: "Vitara Brezza", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Ertiga", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "XL6", fuelTypes: ["Petrol", "CNG"] },
      { name: "Ciaz", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Eeco", fuelTypes: ["Petrol", "CNG"] },
      { name: "Omni", fuelTypes: ["Petrol", "CNG"] },
      { name: "Zen", fuelTypes: ["Petrol"] },
      { name: "Esteem", fuelTypes: ["Petrol"] },
      { name: "SX4", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Ritz", fuelTypes: ["Petrol", "Diesel"] },
      { name: "800", fuelTypes: ["Petrol"] },
      { name: "Grand Vitara", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Gypsy", fuelTypes: ["Petrol"] },
    ],
  },
  {
    name: "Hyundai",
    models: [
      { name: "i10", fuelTypes: ["Petrol", "CNG"] },
      { name: "Grand i10", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "Grand i10 Nios", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "i20", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Aura", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "Verna", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Creta", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Venue", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Tucson", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Elantra", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Sonata", fuelTypes: ["Petrol"] },
      { name: "Santro", fuelTypes: ["Petrol", "CNG"] },
      { name: "Getz", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Accent", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Xcent", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "Elite i20", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Alcazar", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Kona Electric", fuelTypes: ["Electric"] },
    ],
  },
  {
    name: "Tata",
    models: [
      { name: "Indica", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Indigo", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Nano", fuelTypes: ["Petrol"] },
      { name: "Tiago", fuelTypes: ["Petrol", "CNG"] },
      { name: "Tigor", fuelTypes: ["Petrol", "CNG"] },
      { name: "Nexon", fuelTypes: ["Petrol", "Diesel", "Electric"] },
      { name: "Harrier", fuelTypes: ["Diesel"] },
      { name: "Safari", fuelTypes: ["Diesel"] },
      { name: "Punch", fuelTypes: ["Petrol", "CNG"] },
      { name: "Altroz", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Sumo", fuelTypes: ["Diesel"] },
      { name: "Safari Storme", fuelTypes: ["Diesel"] },
      { name: "Aria", fuelTypes: ["Diesel"] },
      { name: "Manza", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Bolt", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Zest", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    name: "Honda",
    models: [
      { name: "City", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "Civic", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Accord", fuelTypes: ["Petrol"] },
      { name: "Jazz", fuelTypes: ["Petrol"] },
      { name: "Amaze", fuelTypes: ["Petrol", "Diesel"] },
      { name: "WR-V", fuelTypes: ["Petrol", "Diesel"] },
      { name: "BR-V", fuelTypes: ["Petrol"] },
      { name: "CR-V", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Brio", fuelTypes: ["Petrol"] },
      { name: "Mobilio", fuelTypes: ["Petrol", "Diesel"] },
      { name: "HR-V", fuelTypes: ["Petrol"] },
    ],
  },
  {
    name: "Toyota",
    models: [
      { name: "Innova", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Innova Crysta", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Fortuner", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Corolla", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Corolla Altis", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Camry", fuelTypes: ["Petrol", "Hybrid"] },
      { name: "Etios", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Etios Liva", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Etios Cross", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Yaris", fuelTypes: ["Petrol"] },
      { name: "Land Cruiser", fuelTypes: ["Diesel", "Petrol"] },
      { name: "Prado", fuelTypes: ["Diesel", "Petrol"] },
      { name: "Qualis", fuelTypes: ["Diesel"] },
      { name: "Glanza", fuelTypes: ["Petrol", "CNG"] },
      { name: "Urban Cruiser", fuelTypes: ["Petrol"] },
      { name: "Hyryder", fuelTypes: ["Petrol", "Hybrid"] },
    ],
  },
  {
    name: "Mahindra",
    models: [
      { name: "Scorpio", fuelTypes: ["Diesel", "Petrol"] },
      { name: "Scorpio-N", fuelTypes: ["Diesel", "Petrol"] },
      { name: "Bolero", fuelTypes: ["Diesel"] },
      { name: "Bolero Neo", fuelTypes: ["Diesel"] },
      { name: "Thar", fuelTypes: ["Diesel", "Petrol"] },
      { name: "XUV500", fuelTypes: ["Diesel", "Petrol"] },
      { name: "XUV300", fuelTypes: ["Petrol", "Diesel"] },
      { name: "XUV400", fuelTypes: ["Electric"] },
      { name: "XUV700", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Marazzo", fuelTypes: ["Diesel"] },
      { name: "Alturas G4", fuelTypes: ["Diesel"] },
      { name: "KUV100", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { name: "Verito", fuelTypes: ["Petrol", "Diesel", "Electric"] },
      { name: "Xylo", fuelTypes: ["Diesel"] },
      { name: "TUV300", fuelTypes: ["Diesel"] },
      { name: "Quanto", fuelTypes: ["Diesel"] },
      { name: "Logan", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    name: "Ford",
    models: [
      { name: "Figo", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Aspire", fuelTypes: ["Petrol", "Diesel"] },
      { name: "EcoSport", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Endeavour", fuelTypes: ["Diesel"] },
      { name: "Freestyle", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Ikon", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Fusion", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Fiesta", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Classic", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    name: "Volkswagen",
    models: [
      { name: "Polo", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Vento", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Ameo", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Tiguan", fuelTypes: ["Petrol"] },
      { name: "Taigun", fuelTypes: ["Petrol"] },
      { name: "Virtus", fuelTypes: ["Petrol"] },
      { name: "Jetta", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Passat", fuelTypes: ["Diesel"] },
    ],
  },
  {
    name: "Skoda",
    models: [
      { name: "Rapid", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Octavia", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Superb", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Kodiaq", fuelTypes: ["Diesel"] },
      { name: "Fabia", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Kushaq", fuelTypes: ["Petrol"] },
      { name: "Slavia", fuelTypes: ["Petrol"] },
      { name: "Laura", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Yeti", fuelTypes: ["Diesel"] },
    ],
  },
  {
    name: "Renault",
    models: [
      { name: "Kwid", fuelTypes: ["Petrol", "CNG"] },
      { name: "Triber", fuelTypes: ["Petrol"] },
      { name: "Kiger", fuelTypes: ["Petrol"] },
      { name: "Duster", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Captur", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Lodgy", fuelTypes: ["Diesel"] },
      { name: "Scala", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Fluence", fuelTypes: ["Diesel"] },
      { name: "Pulse", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    name: "Nissan",
    models: [
      { name: "Micra", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Sunny", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Terrano", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Kicks", fuelTypes: ["Petrol"] },
      { name: "Magnite", fuelTypes: ["Petrol"] },
      { name: "X-Trail", fuelTypes: ["Diesel"] },
      { name: "Evalia", fuelTypes: ["Diesel"] },
    ],
  },
  {
    name: "Kia",
    models: [
      { name: "Seltos", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Sonet", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Carens", fuelTypes: ["Petrol", "Diesel"] },
      { name: "EV6", fuelTypes: ["Electric"] },
      { name: "Carnival", fuelTypes: ["Diesel"] },
    ],
  },
  {
    name: "MG (Morris Garages)",
    models: [
      { name: "Hector", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
      { name: "Hector Plus", fuelTypes: ["Petrol", "Diesel"] },
      { name: "ZS EV", fuelTypes: ["Electric"] },
      { name: "Astor", fuelTypes: ["Petrol"] },
      { name: "Gloster", fuelTypes: ["Diesel"] },
    ],
  },
  {
    name: "Mitsubishi",
    models: [
      { name: "Pajero", fuelTypes: ["Diesel"] },
      { name: "Pajero Sport", fuelTypes: ["Diesel"] },
      { name: "Outlander", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Lancer", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Cedia", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    name: "Chevrolet",
    models: [
      { name: "Beat", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Spark", fuelTypes: ["Petrol"] },
      { name: "Aveo", fuelTypes: ["Petrol"] },
      { name: "Aveo U-VA", fuelTypes: ["Petrol"] },
      { name: "Optra", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Cruze", fuelTypes: ["Diesel"] },
      { name: "Sail", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Tavera", fuelTypes: ["Diesel"] },
      { name: "Captiva", fuelTypes: ["Diesel"] },
      { name: "Enjoy", fuelTypes: ["Diesel"] },
    ],
  },
  {
    name: "Fiat",
    models: [
      { name: "Palio", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Punto", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Linea", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Avventura", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Abarth 595", fuelTypes: ["Petrol"] },
      { name: "Uno", fuelTypes: ["Petrol"] },
    ],
  },
  {
    name: "Mercedes-Benz",
    models: [
      { name: "C-Class", fuelTypes: ["Petrol", "Diesel"] },
      { name: "E-Class", fuelTypes: ["Petrol", "Diesel"] },
      { name: "S-Class", fuelTypes: ["Petrol", "Diesel"] },
      { name: "GLA", fuelTypes: ["Petrol", "Diesel"] },
      { name: "GLC", fuelTypes: ["Petrol", "Diesel"] },
      { name: "GLE", fuelTypes: ["Diesel"] },
      { name: "GLS", fuelTypes: ["Diesel"] },
      { name: "A-Class", fuelTypes: ["Petrol"] },
    ],
  },
  {
    name: "BMW",
    models: [
      { name: "3 Series", fuelTypes: ["Petrol", "Diesel"] },
      { name: "5 Series", fuelTypes: ["Petrol", "Diesel"] },
      { name: "7 Series", fuelTypes: ["Petrol", "Diesel"] },
      { name: "X1", fuelTypes: ["Petrol", "Diesel"] },
      { name: "X3", fuelTypes: ["Petrol", "Diesel"] },
      { name: "X5", fuelTypes: ["Diesel", "Petrol"] },
      { name: "1 Series", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    name: "Audi",
    models: [
      { name: "A4", fuelTypes: ["Petrol", "Diesel"] },
      { name: "A6", fuelTypes: ["Diesel"] },
      { name: "A8", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Q3", fuelTypes: ["Petrol", "Diesel"] },
      { name: "Q5", fuelTypes: ["Diesel"] },
      { name: "Q7", fuelTypes: ["Diesel"] },
    ],
  },
];

export const YEARS: number[] = Array.from(
  { length: 2024 - 2000 + 1 },
  (_, i) => 2024 - i
);
